// Roles
export const JoinRoles = [
  'Gas Delivery Officer',
  'Partner Gas Plant',
  'Bad Cylinder Replacement',
  'Logistic Outfit',
];

// Nigerian states and their cities
export const NigerianCities: Record<string, string[]> = {
  abuja: ['Abuja', 'Kuje', 'Kwali', 'Madala'],
  lagos: [
    'Apapa',
    'Badagry',
    'Ebute Ikorodu',
    'Ejirin',
    'Epe',
    'Ikeja',
    'Lagos',
    'Lekki',
    'Ikorodu',
    'Ojo',
    'Makoko',
    'Agege',
    'Akesan',
    'Iyana Ishashi',
    'Alaska',
    'UNILAG',
    'Ojodu',
    'Mushin',
    'Ikotun',
    'Ijegun',
    'Surulere',
    'Somolu',
    'Ebute Meta',
    'Festac Town',
    'Satellite Town',
    'Victoria Island',
    'Elegushi',
    'VGC',
    'Ajah',
    'Ibeju',
    'Sangotedo',
    'Lambasa',
    'Lakowe',
    'Kajola',
    'Elulu',
    'Ayeteju',
    'Eleko',
    'Araromi',
    'Okunegun',
  ],
  rivers: [
    'Port Harcourt',
    'Bonny',
    'Opobo',
    'Omoku',
    'Eleme',
    'Okrika',
    'Bori',
    'Ahoada',
    'Degema',
    'Abonnema',
    'Isiokpo',
    'Omagwa',
    'Tai',
    'Nkoro',
    'Andoni',
  ],
};
